image: robmellett/lemp:7.3

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ssh-add <(echo "$SERVER_PRIVATE_KEY")

deploy_production:
  only:
    - master
  script:
    - pwd && ls -la
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - yarn install
    - yarn production
    - vendor/bin/phpunit
    - rsync -rlD --progress -e ssh '.' $USER@$SERVER:/var/www/$PROJECT --exclude=".env" --exclude=".git"
    - ssh $USER@$SERVER "cd /var/www/$PROJECT && php artisan migrate --force"
